  - name: Deleting old artifact
    debug: msg="Deleting old artifact; There will be 1 route to new app"

  - name: Delete old green artifact
    command: cf delete {{ app_name }}-green -f
    when: color == "blue"

  - name: Delete old blue artifact
    command: cf delete {{ app_name }}-blue -f
    when: color == "green"