  - name: Rollback from route 4 deploy
    debug: msg="Delete new app"

  - name: Delete new green artifact
    command: cf delete {{ app_name }}-green -f
    when: color == "green"

  - name: Delete new blue artifact
    command: cf delete {{ app_name }}-blue -f
    when: color == "blue"